### ISSUE TITLE
Null pointer when clicking start

### ISSUE THREAD

**Issue by egold555** [RubbaBoy/MSPaintIDE#2]
Followed the startup directions and clicked start and got this error message:

C:\MSPaintIDE>java -jar MSPaintIDE-2.0.1-SNAPSHOT.jar
Scanning all images...
Index keys:
        [!, ", #, $, %, &, ', (, ), *, +, ,, -, ., /, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, :, ;, <, =, >, ?, @, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, [, \, ], ^, _, `, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, {, |, }, ~]
Finished scanning all images in 142ms
Scanning all images...
Finished highlighting all images in 0ms
Finished writing to file in 0ms
Compiling...
Error happened! Thread Thread[Thread-6,5,main] exception: null
java.lang.NullPointerException
        at com.uddernetworks.mspaint.main.CodeCompiler.compile(CodeCompiler.java:73)
        at com.uddernetworks.mspaint.main.CodeCompiler.compileAndExecute(CodeCompiler.java:149)
        at com.uddernetworks.mspaint.main.Main.compile(Main.java:209)
        at com.uddernetworks.mspaint.main.MainGUI.lambda$startScan$3(MainGUI.java:174)
        at java.lang.Thread.run(Unknown Source)

**Comment by RubbaBoy** [comment]
You need to start the program via the JDK as shown in the instructions. See https://github.com/RubbaBoy/MSPaintIDE#usage-tutorial

**Comment by egold555** [comment]
Whoops! I missed that part. Thanks!
